// Generates platform outputs from src/tokens.json:
//   dist/tokens.js + dist/tokens.d.ts  -> JS/TS consumers
//   dist/theme.css                     -> Tailwind v4 `@theme` block (apps/web, apps/admin)
//   apps/mobile/lib/core/theme/tokens.g.dart -> Flutter theme constants
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'src/tokens.json'), 'utf8'));

export function flattenColors(color) {
  const out = [];
  for (const [name, value] of Object.entries(color)) {
    if (typeof value === 'string') out.push([name, value]);
    else for (const [shade, hex] of Object.entries(value)) out.push([`${name}-${shade}`, hex]);
  }
  return out;
}

export function toCss(t) {
  const lines = ['/* Generated by @sajha/design-tokens. Do not edit. */', '@theme {'];
  for (const [name, hex] of flattenColors(t.color)) lines.push(`  --color-${name}: ${hex};`);
  for (const [name, family] of Object.entries(t.font))
    lines.push(`  --font-${name}: '${family}', ui-sans-serif, system-ui, sans-serif;`);
  for (const [name, px] of Object.entries(t.radius)) lines.push(`  --radius-${name}: ${px}px;`);
  lines.push('}', '');
  return lines.join('\n');
}

export function toDts(t) {
  const type = (v, indent) =>
    typeof v === 'object'
      ? `{\n${Object.entries(v)
          .map(([k, x]) => `${indent}  readonly ${JSON.stringify(k)}: ${type(x, indent + '  ')};`)
          .join('\n')}\n${indent}}`
      : typeof v;
  return `declare const tokens: ${type(t, '')};\nexport { tokens };\nexport default tokens;\n`;
}

const camel = (s) => s.replace(/-(\w)/g, (_, c) => c.toUpperCase());
const dartColor = (hex) => `Color(0xFF${hex.replace('#', '').toUpperCase()})`;

export function toDart(t) {
  const colors = flattenColors(t.color)
    .map(
      ([name, hex]) => `  static const ${camel(name.replace(/-(\d)/, '$1'))} = ${dartColor(hex)};`,
    )
    .join('\n');
  const radii = Object.entries(t.radius)
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join('\n');
  const spacing = Object.entries(t.spacing)
    .map(([k, v]) => `  static const double ${k.replace(/^(\d)/, 'x$1')} = ${v};`)
    .join('\n');
  const fonts = Object.entries(t.font)
    .map(([k, v]) => `  static const ${k} = '${v}';`)
    .join('\n');
  return `// Generated by @sajha/design-tokens (pnpm tokens). Do not edit.
// ignore_for_file: constant_identifier_names
import 'package:flutter/painting.dart';

abstract final class SajhaColors {
${colors}
}

abstract final class SajhaRadius {
${radii}
}

abstract final class SajhaSpacing {
${spacing}
}

abstract final class SajhaFonts {
${fonts}
}
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(resolve(root, 'dist'), { recursive: true });
  writeFileSync(resolve(root, 'dist/theme.css'), toCss(tokens));
  writeFileSync(
    resolve(root, 'dist/tokens.js'),
    `export const tokens = ${JSON.stringify(tokens, null, 2)};\nexport default tokens;\n`,
  );
  writeFileSync(resolve(root, 'dist/tokens.d.ts'), toDts(tokens));
  const dartOut = resolve(root, '../../apps/mobile/lib/core/theme/tokens.g.dart');
  mkdirSync(dirname(dartOut), { recursive: true });
  writeFileSync(dartOut, toDart(tokens));
  console.log('design-tokens: wrote dist/theme.css, dist/tokens.js, apps/mobile/.../tokens.g.dart');
}
