// Generates platform outputs from src/tokens.json:
//   dist/tokens.js + dist/tokens.d.ts  -> JS/TS consumers
//   dist/theme.css                     -> Tailwind v4 `@theme` block (apps/web, apps/admin)
//   apps/mobile/lib/core/theme/tokens.g.dart -> Flutter theme constants
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'src/tokens.json'), 'utf8'));

export function flattenColors(color) {
  const out = [];
  for (const [name, value] of Object.entries(color)) {
    if (typeof value === 'string') out.push([name, value]);
    else for (const [shade, hex] of Object.entries(value)) out.push([`${name}-${shade}`, hex]);
  }
  return out;
}

/** "{ink.50}" → the hex of ink-50; plain values pass through. */
export function resolveRef(t, value) {
  const m = /^\{([\w-]+)(?:\.([\w-]+))?\}$/.exec(value);
  if (!m) return value;
  const found = m[2] ? t.color[m[1]]?.[m[2]] : t.color[m[1]];
  if (typeof found !== 'string') throw new Error(`Unknown colour reference ${value}`);
  return found;
}

const rgba = (hex, alpha) => {
  const n = parseInt(hex.slice(1), 16);
  return `rgb(${(n >> 16) & 255} ${(n >> 8) & 255} ${n & 255} / ${alpha})`;
};

export function shadowCss(layers) {
  return layers
    .map((l) => `${l.x}px ${l.y}px ${l.blur}px ${l.spread}px ${rgba(l.color, l.alpha)}`)
    .join(', ');
}

const px = (n) => `${n}px`;

export function toCss(t) {
  const lines = ['/* Generated by @sajha/design-tokens. Do not edit. */', '@theme {'];
  for (const [name, hex] of flattenColors(t.color)) lines.push(`  --color-${name}: ${hex};`);
  for (const [name, family] of Object.entries(t.font))
    lines.push(`  --font-${name}: '${family}', ui-sans-serif, system-ui, sans-serif;`);
  for (const [name, n] of Object.entries(t.radius)) lines.push(`  --radius-${name}: ${px(n)};`);
  for (const [name, layers] of Object.entries(t.shadow ?? {}))
    lines.push(`  --shadow-${name}: ${shadowCss(layers)};`);
  for (const [name, s] of Object.entries(t.typeScale ?? {})) {
    lines.push(`  --text-${name}: ${px(s.size)};`);
    lines.push(`  --text-${name}--line-height: ${px(s.line)};`);
    lines.push(`  --text-${name}--font-weight: ${s.weight};`);
    lines.push(`  --text-${name}--letter-spacing: ${s.tracking}em;`);
  }
  for (const [name, [a, b, c, d]] of Object.entries(t.motion?.easing ?? {}))
    lines.push(`  --ease-${name}: cubic-bezier(${a}, ${b}, ${c}, ${d});`);
  lines.push('}', '');
  if (t.semantic) {
    // Semantic roles as variables (light by default, `.dark` flips them), and as
    // Tailwind colours: bg-sj-primary, text-sj-muted-foreground, border-sj-border…
    const vars = (mode) =>
      Object.entries(t.semantic[mode]).map(([k, v]) => `  --sj-${k}: ${resolveRef(t, v)};`);
    const extra = [
      ...Object.entries(t.size?.control ?? {}).map(([k, v]) => `  --sj-control-${k}: ${px(v)};`),
      ...Object.entries(t.size?.icon ?? {}).map(([k, v]) => `  --sj-icon-${k}: ${px(v)};`),
      ...Object.entries(t.motion?.duration ?? {}).map(([k, v]) => `  --sj-duration-${k}: ${v}ms;`),
    ];
    lines.push(':root {', ...vars('light'), ...extra, '}', '');
    lines.push('.dark {', ...vars('dark'), '}', '');
    lines.push('@theme inline {');
    for (const k of Object.keys(t.semantic.light)) lines.push(`  --color-sj-${k}: var(--sj-${k});`);
    lines.push('}', '');
  }
  return lines.join('\n');
}

export function toDts(t) {
  const type = (v, indent) =>
    typeof v === 'object'
      ? `{\n${Object.entries(v)
          .map(([k, x]) => `${indent}  readonly ${JSON.stringify(k)}: ${type(x, indent + '  ')};`)
          .join('\n')}\n${indent}}`
      : typeof v;
  return `declare const tokens: ${type(t, '')};\nexport { tokens };\nexport default tokens;\n`;
}

const camel = (s) => s.replace(/-(\w)/g, (_, c) => c.toUpperCase());
const dartColor = (hex) => `Color(0xFF${hex.replace('#', '').toUpperCase()})`;

export function toDart(t) {
  const colors = flattenColors(t.color)
    .map(
      ([name, hex]) => `  static const ${camel(name.replace(/-(\d)/, '$1'))} = ${dartColor(hex)};`,
    )
    .join('\n');
  const radii = Object.entries(t.radius)
    .map(([k, v]) => `  static const double ${k} = ${v};`)
    .join('\n');
  const spacing = Object.entries(t.spacing)
    .map(([k, v]) => `  static const double ${k.replace(/^(\d)/, 'x$1')} = ${v};`)
    .join('\n');
  const fonts = Object.entries(t.font)
    .map(([k, v]) => `  static const ${k} = '${v}';`)
    .join('\n');
  const extra = t.semantic ? dartExtras(t) : '';
  return `// Generated by @sajha/design-tokens (pnpm tokens). Do not edit.
// ignore_for_file: constant_identifier_names
import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

abstract final class SajhaColors {
${colors}
}

abstract final class SajhaRadius {
${radii}
}

abstract final class SajhaSpacing {
${spacing}
}

abstract final class SajhaFonts {
${fonts}
}
${extra}`;
}

const dartDouble = (n) => (Number.isInteger(n) ? `${n}` : `${n}`);
const round = (n) => Math.round(n * 1000) / 1000;

/** Semantic colours, the type scale, shadows, motion and sizes (Phase 11). */
export function dartExtras(t) {
  const out = [];
  for (const [mode, cls] of [
    ['light', 'SajhaLight'],
    ['dark', 'SajhaDark'],
  ]) {
    const rows = Object.entries(t.semantic[mode])
      .map(([k, v]) => `  static const ${camel(k)} = ${dartColor(resolveRef(t, v))};`)
      .join('\n');
    out.push(
      `\n/// Semantic colours (${mode}); see DESIGN.md.\nabstract final class ${cls} {\n${rows}\n}\n`,
    );
  }
  const weight = (w) => `FontWeight.w${w}`;
  const type = Object.entries(t.typeScale)
    .map(
      ([k, s]) => `  static const ${k} = TextStyle(
    fontFamily: SajhaFonts.${s.font},
    fontSize: ${s.size},
    height: ${round(s.line / s.size)},
    fontWeight: ${weight(s.weight)},
    letterSpacing: ${round(s.tracking * s.size)},
  );`,
    )
    .join('\n');
  out.push(
    `\n/// The one type scale for every app (DESIGN.md).\nabstract final class SajhaType {\n${type}\n}\n`,
  );
  const color = (l) =>
    `Color(0x${Math.round(l.alpha * 255)
      .toString(16)
      .padStart(2, '0')
      .toUpperCase()}${l.color.replace('#', '').toUpperCase()})`;
  const shadows = Object.entries(t.shadow)
    .map(
      ([k, layers]) =>
        `  static const ${k} = [\n${layers
          .map(
            (l) =>
              `    BoxShadow(\n      color: ${color(l)},\n      offset: Offset(${l.x}, ${l.y}),\n      blurRadius: ${l.blur},\n      spreadRadius: ${l.spread},\n    ),`,
          )
          .join('\n')}\n  ];`,
    )
    .join('\n');
  out.push(`\nabstract final class SajhaShadow {\n${shadows}\n}\n`);
  const durations = Object.entries(t.motion.duration)
    .map(([k, v]) => `  static const ${k} = Duration(milliseconds: ${v});`)
    .join('\n');
  const easings = Object.entries(t.motion.easing)
    .map(([k, [a, b, c, d]]) => `  static const ${k} = Cubic(${dartDouble(a)}, ${b}, ${c}, ${d});`)
    .join('\n');
  out.push(`\nabstract final class SajhaMotion {\n${durations}\n${easings}\n}\n`);
  const sizes = [
    ...Object.entries(t.size.control).map(
      ([k, v]) => `  static const double control${k[0].toUpperCase() + k.slice(1)} = ${v};`,
    ),
    ...Object.entries(t.size.icon).map(
      ([k, v]) => `  static const double icon${k[0].toUpperCase() + k.slice(1)} = ${v};`,
    ),
    `  static const double border = ${t.size.border};`,
  ].join('\n');
  out.push(`\nabstract final class SajhaSize {\n${sizes}\n}\n`);
  return out.join('');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(resolve(root, 'dist'), { recursive: true });
  writeFileSync(resolve(root, 'dist/theme.css'), toCss(tokens));
  writeFileSync(
    resolve(root, 'dist/tokens.js'),
    `export const tokens = ${JSON.stringify(tokens, null, 2)};\nexport default tokens;\n`,
  );
  writeFileSync(resolve(root, 'dist/tokens.d.ts'), toDts(tokens));
  const dartOut = resolve(root, '../../apps/mobile/lib/core/theme/tokens.g.dart');
  mkdirSync(dirname(dartOut), { recursive: true });
  writeFileSync(dartOut, toDart(tokens));
  console.log('design-tokens: wrote dist/theme.css, dist/tokens.js, apps/mobile/.../tokens.g.dart');
}
