/**
 * Stable, machine-readable error codes returned in `{ error: { code } }`.
 * Clients switch on these; never rename one that has shipped.
 */
export const ErrorCode = {
  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',

  // OTP (app users)
  PHONE_INVALID: 'PHONE_INVALID',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_DELIVERY_FAILED: 'OTP_DELIVERY_FAILED',
  EMAIL_IN_USE: 'EMAIL_IN_USE',

  // tokens & sessions (both realms)
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_REUSED: 'REFRESH_REUSED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // admin
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_INVALID: 'MFA_INVALID',
  MFA_SETUP_REQUIRED: 'MFA_SETUP_REQUIRED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_REUSED: 'PASSWORD_REUSED',
  ADMIN_EMAIL_IN_USE: 'ADMIN_EMAIL_IN_USE',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
