/**
 * Stable, machine-readable error codes returned in `{ error: { code } }`.
 * Clients switch on these; never rename one that has shipped.
 */
export const ErrorCode = {
  // generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMITED: 'RATE_LIMITED',

  // OTP (app users)
  PHONE_INVALID: 'PHONE_INVALID',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  OTP_RATE_LIMITED: 'OTP_RATE_LIMITED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_DELIVERY_FAILED: 'OTP_DELIVERY_FAILED',
  EMAIL_IN_USE: 'EMAIL_IN_USE',

  // tokens & sessions (both realms)
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_REUSED: 'REFRESH_REUSED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',

  // admin
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  MFA_INVALID: 'MFA_INVALID',
  MFA_SETUP_REQUIRED: 'MFA_SETUP_REQUIRED',
  MFA_ALREADY_ENABLED: 'MFA_ALREADY_ENABLED',
  PASSWORD_CHANGE_REQUIRED: 'PASSWORD_CHANGE_REQUIRED',
  PASSWORD_REUSED: 'PASSWORD_REUSED',
  ADMIN_EMAIL_IN_USE: 'ADMIN_EMAIL_IN_USE',
  CANNOT_MODIFY_SELF: 'CANNOT_MODIFY_SELF',

  // uploads, profiles & documents
  UPLOAD_NOT_FOUND: 'UPLOAD_NOT_FOUND',
  UPLOAD_INVALID: 'UPLOAD_INVALID',
  UPLOAD_RATE_LIMITED: 'UPLOAD_RATE_LIMITED',
  DOCUMENT_ALREADY_EXISTS: 'DOCUMENT_ALREADY_EXISTS',
  DOCUMENT_NOT_PENDING: 'DOCUMENT_NOT_PENDING',
  VERIFICATION_REQUIRED: 'VERIFICATION_REQUIRED',
  USER_STATUS_CONFLICT: 'USER_STATUS_CONFLICT',

  // listings & categories
  LISTING_INCOMPLETE: 'LISTING_INCOMPLETE',
  LISTING_STATUS_CONFLICT: 'LISTING_STATUS_CONFLICT',
  LISTING_PHOTO_LIMIT: 'LISTING_PHOTO_LIMIT',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',

  // discovery
  FAVORITE_OWN_LISTING: 'FAVORITE_OWN_LISTING',

  // chat, offers, safety
  CONVERSATION_NOT_ALLOWED: 'CONVERSATION_NOT_ALLOWED',
  USER_BLOCKED: 'USER_BLOCKED',
  OFFER_NOT_PENDING: 'OFFER_NOT_PENDING',
  OFFER_EXPIRED: 'OFFER_EXPIRED',
  OFFER_DATES_UNAVAILABLE: 'OFFER_DATES_UNAVAILABLE',
  OFFER_OWN: 'OFFER_OWN',
  REPORT_DUPLICATE: 'REPORT_DUPLICATE',
  REPORT_STATUS_CONFLICT: 'REPORT_STATUS_CONFLICT',

  // bookings, document sharing
  BOOKING_NOT_ALLOWED: 'BOOKING_NOT_ALLOWED',
  BOOKING_OWN_LISTING: 'BOOKING_OWN_LISTING',
  BOOKING_DATES_UNAVAILABLE: 'BOOKING_DATES_UNAVAILABLE',
  BOOKING_DATES_TAKEN: 'BOOKING_DATES_TAKEN',
  BOOKING_OPEN_EXISTS: 'BOOKING_OPEN_EXISTS',
  BOOKING_INVALID_TRANSITION: 'BOOKING_INVALID_TRANSITION',
  BOOKING_DOCS_MISMATCH: 'BOOKING_DOCS_MISMATCH',
  DOCUMENT_ACCESS_ENDED: 'DOCUMENT_ACCESS_ENDED',
  LISTING_HAS_OPEN_BOOKINGS: 'LISTING_HAS_OPEN_BOOKINGS',
  ACCOUNT_HAS_OPEN_BOOKINGS: 'ACCOUNT_HAS_OPEN_BOOKINGS',

  // payments, refunds, payouts
  PAYMENT_NOT_ALLOWED: 'PAYMENT_NOT_ALLOWED',
  PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
  PAYMENT_PROVIDER_ERROR: 'PAYMENT_PROVIDER_ERROR',
  REFUND_TOO_LARGE: 'REFUND_TOO_LARGE',
  PAYOUT_ACCOUNT_INVALID: 'PAYOUT_ACCOUNT_INVALID',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',

  // handover, return, disputes, reviews
  BOOKING_CODE_INVALID: 'BOOKING_CODE_INVALID',
  BOOKING_CODE_LOCKED: 'BOOKING_CODE_LOCKED',
  HANDOVER_TOO_EARLY: 'HANDOVER_TOO_EARLY',
  PHOTOS_REQUIRED: 'PHOTOS_REQUIRED',
  DISPUTE_WINDOW_CLOSED: 'DISPUTE_WINDOW_CLOSED',
  KEEP_TOO_LARGE: 'KEEP_TOO_LARGE',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
