import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Transform } from 'class-transformer';
import {
  IsEmail,
  IsIn,
  IsOptional,
  IsString,
  IsUUID,
  Length,
  Matches,
  MaxLength,
} from 'class-validator';
import { UserDto } from '../../users/dto/user.dto.js';

const trim = ({ value }: { value: unknown }) => (typeof value === 'string' ? value.trim() : value);

export class RequestPhoneOtpDto {
  @ApiProperty({ example: '9876543210', description: 'Indian mobile number, any common format' })
  @IsString()
  @MaxLength(20)
  phone: string;
}

export class OtpChallengeDto {
  @ApiProperty({ format: 'uuid' }) challengeId: string;
  @ApiProperty({ example: 300 }) expiresInSec: number;
  @ApiProperty({ example: 30 }) resendAfterSec: number;
}

export class VerifyPhoneOtpDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  challengeId: string;

  @ApiProperty({ example: '123456' })
  @Matches(/^\d{6}$/, { message: 'code must be 6 digits' })
  code: string;

  @ApiProperty({ description: 'Stable per-install id generated by the app', example: 'b1c9…' })
  @IsString()
  @Length(8, 128)
  deviceId: string;

  @ApiPropertyOptional({ example: 'Pixel 8' })
  @IsOptional()
  @IsString()
  @MaxLength(120)
  @Transform(trim)
  deviceName?: string;

  @ApiPropertyOptional({ enum: ['android', 'ios'] })
  @IsOptional()
  @IsIn(['android', 'ios'])
  platform?: string;
}

export class TokensDto {
  @ApiProperty() accessToken: string;
  @ApiProperty() refreshToken: string;
  @ApiProperty({ example: 900 }) expiresInSec: number;
}

export class LoginResponseDto extends TokensDto {
  @ApiProperty({ description: 'True the first time this phone number signs in' })
  isNewUser: boolean;

  @ApiProperty({ type: UserDto }) user: UserDto;
}

export class RefreshDto {
  @ApiProperty()
  @IsString()
  @Length(16, 256)
  refreshToken: string;
}

export class RequestEmailOtpDto {
  @ApiProperty({ example: 'rahul@example.com' })
  @Transform(({ value }) => (typeof value === 'string' ? value.trim().toLowerCase() : value))
  @IsEmail()
  @MaxLength(254)
  email: string;
}

export class VerifyEmailOtpDto {
  @ApiProperty({ format: 'uuid' })
  @IsUUID()
  challengeId: string;

  @ApiProperty({ example: '123456' })
  @Matches(/^\d{6}$/, { message: 'code must be 6 digits' })
  code: string;
}

export class UserResponseDto {
  @ApiProperty({ type: UserDto }) user: UserDto;
}
