#!/usr/bin/env bash
# Deploys the Nivra backend on one Linux VM (Oracle Cloud Always Free works)
# and prints its public https address. Safe to re-run: it updates and restarts.
#
#   scripts/oracle-deploy.sh                    # quick tunnel: random https://….trycloudflare.com
#   CLOUDFLARE_TUNNEL_TOKEN=… PUBLIC_HOST=api.example.com scripts/oracle-deploy.sh
#                                               # named tunnel on your own hostname (stable)
#   DOMAIN=api.example.com scripts/oracle-deploy.sh
#                                               # your domain straight at the VM, ports 80/443
#   MODE=local scripts/oracle-deploy.sh         # try it on a laptop: http://localhost:8080
#   SKIP_BUILD=1 …                              # reuse an nivra-api:local image you built yourself
#
# Secrets are generated on the first run into infra/oracle/.env (never
# committed, never overwritten). The mode and address are remembered there, so
# later runs (e.g. after `git pull`) need no arguments. See docs/ORACLE.md.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/infra/oracle"
ENV_FILE="$DIR/.env"
SUDO=""
[ "$(id -u)" -eq 0 ] || SUDO="sudo"

say() { printf '\n==> %s\n' "$*"; }
die() { printf '\nError: %s\n' "$*" >&2; exit 1; }

# ── Mode (remembered in .env, so a plain re-run keeps the same setup) ──
saved() { [ -f "$ENV_FILE" ] && grep "^$1=" "$ENV_FILE" | tail -1 | cut -d= -f2- || true; }
: "${DOMAIN:=$(saved DOMAIN)}"
: "${PUBLIC_HOST:=$(saved PUBLIC_HOST)}"
: "${CLOUDFLARE_TUNNEL_TOKEN:=$(saved CLOUDFLARE_TUNNEL_TOKEN)}"
: "${MODE:=$(saved DEPLOY_MODE)}"
if [ -z "${MODE:-}" ]; then
  if [ -n "${DOMAIN:-}" ]; then MODE=domain
  elif [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ]; then MODE=named
  else MODE=quick
  fi
fi
case "$MODE" in
  quick | named | domain | local) ;;
  *) die "MODE must be quick, named, domain or local" ;;
esac
[ "$MODE" != named ] || [ -n "${PUBLIC_HOST:-}" ] || die "a named tunnel needs PUBLIC_HOST (the hostname you set on the tunnel)"
[ "$MODE" != named ] || [ -n "${CLOUDFLARE_TUNNEL_TOKEN:-}" ] || die "a named tunnel needs CLOUDFLARE_TUNNEL_TOKEN"

# ── Tools ──
install_pkgs() {
  if command -v apt-get >/dev/null; then
    $SUDO apt-get update -qq && $SUDO apt-get install -y -qq "$@"
  elif command -v dnf >/dev/null; then
    $SUDO dnf install -y -q "$@"
  else
    die "install $* first"
  fi
}
for tool in curl git jq openssl; do
  command -v "$tool" >/dev/null || install_pkgs "$tool"
done

if ! command -v docker >/dev/null; then
  say "Installing Docker"
  . /etc/os-release
  if [ "${ID:-}" = ol ] || [ "${ID:-}" = rhel ] || [ "${ID:-}" = centos ]; then
    $SUDO dnf install -y -q dnf-plugins-core
    $SUDO dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    $SUDO dnf install -y -q docker-ce docker-ce-cli containerd.io docker-compose-plugin
  else
    curl -fsSL https://get.docker.com | $SUDO sh
  fi
  $SUDO systemctl enable --now docker
fi
docker compose version >/dev/null 2>&1 || die "the Docker compose plugin is missing (install docker-compose-plugin)"
DOCKER="docker"
docker info >/dev/null 2>&1 || DOCKER="$SUDO docker"

FILES=(-f "$DIR/docker-compose.yml")
PROFILES=()
case "$MODE" in
  quick) PROFILES=(--profile quick) ;;
  named) PROFILES=(--profile named) ;;
  domain) FILES+=(-f "$DIR/docker-compose.domain.yml") ;;
  local) FILES+=(-f "$DIR/docker-compose.local.yml") ;;
esac
compose() { $DOCKER compose --project-directory "$DIR" --env-file "$ENV_FILE" "${FILES[@]}" "${PROFILES[@]}" "$@"; }

# ── Secrets (first run only) ──
rand() { openssl rand -base64 "$1" | tr -d '\n'; }
hex() { openssl rand -hex "$1"; }
if [ ! -f "$ENV_FILE" ]; then
  say "Generating secrets in infra/oracle/.env"
  umask 077
  pg_pass="$(hex 24)"
  s3_key="nivra$(hex 6)"
  s3_secret="$(hex 24)"
  cat >"$ENV_FILE" <<ENV
# Nivra on this VM. Generated by scripts/oracle-deploy.sh; keep it private.
# Pre-launch test server: SMS codes, push and payments are simulated (see
# docs/ORACLE.md, "Going live", for switching to MSG91, FCM, Resend and Razorpay).
NODE_ENV=test
PORT=3000
LOG_LEVEL=info
SWAGGER_ENABLED=false
SENTRY_ENVIRONMENT=vm

POSTGRES_PASSWORD=$pg_pass
DATABASE_URL=postgresql://sajha:$pg_pass@postgres:5432/sajha?schema=public
REDIS_URL=redis://redis:6379

JWT_ACCESS_SECRET=$(rand 48)
JWT_ADMIN_ACCESS_SECRET=$(rand 48)
ACCESS_TOKEN_TTL_SEC=900
REFRESH_TOKEN_TTL_DAYS=30
ADMIN_ACCESS_TOKEN_TTL_SEC=600
ADMIN_REFRESH_TOKEN_TTL_HOURS=12
OTP_PEPPER=$(rand 48)
OTP_DEV_BYPASS_CODE=
TOTP_ENC_KEY=$(rand 32)
ADDRESS_ENC_KEY=$(rand 32)
TOTP_ISSUER=Nivra Admin

# console = codes are printed to the API log: docker compose logs api | grep OTP
SMS_PROVIDER=console
MSG91_AUTH_KEY=
MSG91_OTP_TEMPLATE_ID=
MSG91_OVERDUE_TEMPLATE_ID=
PUSH_PROVIDER=console
FCM_PROJECT_ID=
FCM_SERVICE_ACCOUNT_JSON=
EMAIL_PROVIDER=smtp
EMAIL_FROM=Nivra <no-reply@sajha.app>
PUBLIC_SITE_URL=https://sajha.app
SMTP_HOST=mailpit
SMTP_PORT=1025
RESEND_API_KEY=

S3_REGION=ap-south-1
S3_ACCESS_KEY_ID=$s3_key
S3_SECRET_ACCESS_KEY=$s3_secret
S3_FORCE_PATH_STYLE=true
S3_PUBLIC_BUCKET=sajha-public-media
S3_PRIVATE_BUCKET=sajha-private-docs
S3_PRIVATE_SSE=none

JOBS_WORKER=true
BOOKING_REQUEST_TTL_MIN=1440
BOOKING_DOCS_TTL_MIN=1440
BOOKING_PAYMENT_TTL_MIN=120
SHARE_RETENTION_DAYS=30

PAYMENT_PROVIDER=fake
RAZORPAY_KEY_ID=
RAZORPAY_KEY_SECRET=
RAZORPAY_WEBHOOK_SECRET=

PUBLIC_READ_LIMIT_PER_MIN=120
SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0

# Set by the script on every run.
GIT_SHA=
SITE_ADDRESS=:80
PUBLIC_URL=
S3_ENDPOINT=
S3_PUBLIC_BASE_URL=
CORS_ORIGINS=
DEPLOY_MODE=
DOMAIN=
PUBLIC_HOST=
CLOUDFLARE_TUNNEL_TOKEN=
# true = photos and documents live in Cloudflare R2 or AWS S3 (set the S3_* values above).
EXTERNAL_S3=false
ENV
fi

# Sets KEY=value in .env (replacing an existing line).
set_env() {
  local key="$1" value="$2" tmp
  tmp="$(mktemp)"
  grep -v "^$key=" "$ENV_FILE" >"$tmp" || true
  printf '%s=%s\n' "$key" "$value" >>"$tmp"
  cat "$tmp" >"$ENV_FILE"
  rm -f "$tmp"
}
get_env() { grep "^$1=" "$ENV_FILE" | tail -1 | cut -d= -f2-; }

# SeaweedFS credentials follow .env; public media is readable without a key.
cat >"$DIR/s3.json" <<JSON
{
  "identities": [
    {
      "name": "nivra",
      "credentials": [{ "accessKey": "$(get_env S3_ACCESS_KEY_ID)", "secretKey": "$(get_env S3_SECRET_ACCESS_KEY)" }],
      "actions": ["Admin", "Read", "List", "Tagging", "Write"]
    },
    { "name": "anonymous", "actions": ["Read:sajha-public-media"] }
  ]
}
JSON
# SeaweedFS runs as a non-root user inside its container, so it must be able to read this.
chmod 644 "$DIR/s3.json"

set_env GIT_SHA "$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo dev)"
set_env DEPLOY_MODE "$MODE"
set_env DOMAIN "${DOMAIN:-}"
set_env PUBLIC_HOST "${PUBLIC_HOST:-}"
set_env CLOUDFLARE_TUNNEL_TOKEN "${CLOUDFLARE_TUNNEL_TOKEN:-}"
case "$MODE" in
  domain) set_env SITE_ADDRESS "$DOMAIN" ;;
  *) set_env SITE_ADDRESS ":80" ;;
esac

# ── Build and start everything but the API ──
if [ -n "${SKIP_BUILD:-}" ]; then
  say "Using the existing nivra-api:local image (SKIP_BUILD)"
else
  say "Building the API image (a few minutes the first time)"
  compose build migrate
fi

say "Starting the database, Redis, storage and the router"
compose up -d postgres redis s3 s3-init mailpit caddy
case "$MODE" in
  quick) compose up -d tunnel-quick ;;
  named) compose up -d tunnel ;;
esac

# ── Public address ──
case "$MODE" in
  quick)
    say "Waiting for the quick tunnel address"
    url=""
    for _ in $(seq 1 60); do
      url="$(compose logs tunnel-quick 2>/dev/null | grep -Eo 'https://[a-z0-9-]+\.trycloudflare\.com' | tail -1 || true)"
      [ -n "$url" ] && break
      sleep 2
    done
    [ -n "$url" ] || die "the quick tunnel did not start; see: docker compose -f infra/oracle/docker-compose.yml logs tunnel-quick"
    ;;
  named) url="https://${PUBLIC_HOST#https://}" ;;
  domain) url="https://${DOMAIN#https://}" ;;
  local) url="http://host.docker.internal:8080" ;;
esac
url="${url%/}"
set_env PUBLIC_URL "$url"
# Built-in storage is served on the same address; with EXTERNAL_S3=true in .env
# (Cloudflare R2 or AWS S3, docs/ORACLE.md) the S3_* values are left as you set them.
if [ "$(get_env EXTERNAL_S3)" != true ]; then
  set_env S3_ENDPOINT "$url"
  set_env S3_PUBLIC_BASE_URL "$url/sajha-public-media"
fi
set_env CORS_ORIGINS "$url"

# ── Migrate and start the API ──
say "Migrating the database and starting the API"
compose run --rm migrate
compose up -d --no-deps --force-recreate api

check_url="$url"
[ "$MODE" = local ] && check_url="http://localhost:8080"
say "Waiting for $check_url/v1/health"
SMOKE_TIMEOUT_SEC="${SMOKE_TIMEOUT_SEC:-240}" "$ROOT/scripts/smoke-test.sh" "$check_url" "$(get_env GIT_SHA)"

cat <<DONE

Nivra is up.

  API address:   $url
  Health:        $url/v1/health

Point the Android app at it: on GitHub, Actions → Build APK → Run workflow,
with api_base_url = $url, then install the new APK.

Handy commands (from $ROOT):
  Sign-in codes:  docker compose -f infra/oracle/docker-compose.yml logs api | grep OTP
  Logs:           docker compose -f infra/oracle/docker-compose.yml logs -f api
  First admin:    docker compose -f infra/oracle/docker-compose.yml exec api node dist/cli/seed-admin.js --email you@example.com --name "Your Name"
  Update:         git pull && scripts/oracle-deploy.sh   (same mode and address as now)
DONE
if [ "$MODE" = quick ]; then
  cat <<'NOTE'

A quick-tunnel address changes whenever the tunnel restarts (for example after
a VM reboot). Re-run scripts/oracle-deploy.sh to pick up the new one, or use a
named tunnel for a permanent address (docs/ORACLE.md).
NOTE
fi
