// Generated by @sajha/design-tokens (pnpm tokens). Do not edit.
// ignore_for_file: constant_identifier_names
import 'package:flutter/animation.dart';
import 'package:flutter/painting.dart';

abstract final class SajhaColors {
  static const brand50 = Color(0xFFEEFBF6);
  static const brand100 = Color(0xFFD5F5E8);
  static const brand200 = Color(0xFFAEEAD4);
  static const brand300 = Color(0xFF78D8BA);
  static const brand400 = Color(0xFF40BF9C);
  static const brand500 = Color(0xFF1DA482);
  static const brand600 = Color(0xFF11846A);
  static const brand700 = Color(0xFF0F6A57);
  static const brand800 = Color(0xFF105447);
  static const brand900 = Color(0xFF0E453B);
  static const brand950 = Color(0xFF062722);
  static const accent50 = Color(0xFFFFF8EB);
  static const accent100 = Color(0xFFFEEAC7);
  static const accent200 = Color(0xFFFDD38A);
  static const accent300 = Color(0xFFFCB64D);
  static const accent400 = Color(0xFFFB9D24);
  static const accent500 = Color(0xFFF57B0B);
  static const accent600 = Color(0xFFD95806);
  static const accent700 = Color(0xFFB43A09);
  static const accent800 = Color(0xFF922D0E);
  static const accent900 = Color(0xFF78260F);
  static const accent950 = Color(0xFF451103);
  static const ink50 = Color(0xFFF6F7F9);
  static const ink100 = Color(0xFFECEEF2);
  static const ink200 = Color(0xFFD5DAE2);
  static const ink300 = Color(0xFFB0B9C9);
  static const ink400 = Color(0xFF8594AB);
  static const ink500 = Color(0xFF667691);
  static const ink600 = Color(0xFF515F78);
  static const ink700 = Color(0xFF434D62);
  static const ink800 = Color(0xFF3A4253);
  static const ink900 = Color(0xFF1F2430);
  static const ink950 = Color(0xFF12151C);
  static const success = Color(0xFF16A34A);
  static const warning = Color(0xFFF59E0B);
  static const danger = Color(0xFFDC2626);
  static const info = Color(0xFF2563EB);
}

abstract final class SajhaRadius {
  static const double sm = 8;
  static const double md = 12;
  static const double lg = 16;
  static const double xl = 24;
  static const double full = 9999;
}

abstract final class SajhaSpacing {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
  static const double x2xl = 48;
}

abstract final class SajhaFonts {
  static const sans = 'Plus Jakarta Sans';
  static const display = 'Bricolage Grotesque';
  static const mono = 'JetBrains Mono';
}

/// Semantic colours (light); see DESIGN.md.
abstract final class SajhaLight {
  static const background = Color(0xFFF6F7F9);
  static const surface = Color(0xFFFFFFFF);
  static const surfaceMuted = Color(0xFFECEEF2);
  static const foreground = Color(0xFF12151C);
  static const mutedForeground = Color(0xFF667691);
  static const border = Color(0xFFD5DAE2);
  static const input = Color(0xFFD5DAE2);
  static const ring = Color(0xFF1DA482);
  static const primary = Color(0xFF11846A);
  static const primaryHover = Color(0xFF0F6A57);
  static const onPrimary = Color(0xFFFFFFFF);
  static const primarySoft = Color(0xFFEEFBF6);
  static const onPrimarySoft = Color(0xFF0F6A57);
  static const accent = Color(0xFFF57B0B);
  static const onAccent = Color(0xFFFFFFFF);
  static const success = Color(0xFF16A34A);
  static const warning = Color(0xFFF59E0B);
  static const danger = Color(0xFFDC2626);
  static const onDanger = Color(0xFFFFFFFF);
  static const info = Color(0xFF2563EB);
}

/// Semantic colours (dark); see DESIGN.md.
abstract final class SajhaDark {
  static const background = Color(0xFF12151C);
  static const surface = Color(0xFF1F2430);
  static const surfaceMuted = Color(0xFF3A4253);
  static const foreground = Color(0xFFF6F7F9);
  static const mutedForeground = Color(0xFF8594AB);
  static const border = Color(0xFF3A4253);
  static const input = Color(0xFF434D62);
  static const ring = Color(0xFF40BF9C);
  static const primary = Color(0xFF40BF9C);
  static const primaryHover = Color(0xFF78D8BA);
  static const onPrimary = Color(0xFF062722);
  static const primarySoft = Color(0xFF0E453B);
  static const onPrimarySoft = Color(0xFFAEEAD4);
  static const accent = Color(0xFFFB9D24);
  static const onAccent = Color(0xFF12151C);
  static const success = Color(0xFF22C55E);
  static const warning = Color(0xFFFBBF24);
  static const danger = Color(0xFFF87171);
  static const onDanger = Color(0xFF12151C);
  static const info = Color(0xFF60A5FA);
}

/// The one type scale for every app (DESIGN.md).
abstract final class SajhaType {
  static const display = TextStyle(
    fontFamily: SajhaFonts.display,
    fontSize: 40,
    height: 1.2,
    fontWeight: FontWeight.w700,
    letterSpacing: -0.8,
  );
  static const h1 = TextStyle(
    fontFamily: SajhaFonts.display,
    fontSize: 32,
    height: 1.25,
    fontWeight: FontWeight.w700,
    letterSpacing: -0.64,
  );
  static const h2 = TextStyle(
    fontFamily: SajhaFonts.display,
    fontSize: 24,
    height: 1.333,
    fontWeight: FontWeight.w700,
    letterSpacing: -0.24,
  );
  static const h3 = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 20,
    height: 1.4,
    fontWeight: FontWeight.w600,
    letterSpacing: 0,
  );
  static const title = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 17,
    height: 1.412,
    fontWeight: FontWeight.w600,
    letterSpacing: 0,
  );
  static const body = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 15,
    height: 1.467,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  );
  static const small = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 13,
    height: 1.385,
    fontWeight: FontWeight.w400,
    letterSpacing: 0,
  );
  static const caption = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 12,
    height: 1.333,
    fontWeight: FontWeight.w500,
    letterSpacing: 0.12,
  );
  static const button = TextStyle(
    fontFamily: SajhaFonts.sans,
    fontSize: 15,
    height: 1.333,
    fontWeight: FontWeight.w600,
    letterSpacing: 0,
  );
  static const mono = TextStyle(
    fontFamily: SajhaFonts.mono,
    fontSize: 13,
    height: 1.385,
    fontWeight: FontWeight.w500,
    letterSpacing: 0,
  );
}

abstract final class SajhaShadow {
  static const xs = [
    BoxShadow(
      color: Color(0x0F12151C),
      offset: Offset(0, 1),
      blurRadius: 2,
      spreadRadius: 0,
    ),
  ];
  static const sm = [
    BoxShadow(
      color: Color(0x1412151C),
      offset: Offset(0, 1),
      blurRadius: 3,
      spreadRadius: 0,
    ),
    BoxShadow(
      color: Color(0x0A12151C),
      offset: Offset(0, 1),
      blurRadius: 2,
      spreadRadius: 0,
    ),
  ];
  static const md = [
    BoxShadow(
      color: Color(0x1F12151C),
      offset: Offset(0, 6),
      blurRadius: 16,
      spreadRadius: -4,
    ),
  ];
  static const lg = [
    BoxShadow(
      color: Color(0x3812151C),
      offset: Offset(0, 16),
      blurRadius: 40,
      spreadRadius: -12,
    ),
  ];
  static const glow = [
    BoxShadow(
      color: Color(0x7311846A),
      offset: Offset(0, 8),
      blurRadius: 24,
      spreadRadius: -6,
    ),
  ];
}

abstract final class SajhaMotion {
  static const fast = Duration(milliseconds: 120);
  static const base = Duration(milliseconds: 200);
  static const slow = Duration(milliseconds: 320);
  static const standard = Cubic(0.2, 0, 0, 1);
  static const emphasized = Cubic(0.3, 0, 0, 1.2);
}

abstract final class SajhaSize {
  static const double controlSm = 36;
  static const double controlMd = 44;
  static const double controlLg = 52;
  static const double iconSm = 16;
  static const double iconMd = 20;
  static const double iconLg = 24;
  static const double border = 1;
}
