// Generated by @sajha/design-tokens (pnpm tokens). Do not edit.
// ignore_for_file: constant_identifier_names
import 'package:flutter/painting.dart';

abstract final class SajhaColors {
  static const brand50 = Color(0xFFEEFBF6);
  static const brand100 = Color(0xFFD5F5E8);
  static const brand200 = Color(0xFFAEEAD4);
  static const brand300 = Color(0xFF78D8BA);
  static const brand400 = Color(0xFF40BF9C);
  static const brand500 = Color(0xFF1DA482);
  static const brand600 = Color(0xFF11846A);
  static const brand700 = Color(0xFF0F6A57);
  static const brand800 = Color(0xFF105447);
  static const brand900 = Color(0xFF0E453B);
  static const brand950 = Color(0xFF062722);
  static const accent50 = Color(0xFFFFF8EB);
  static const accent100 = Color(0xFFFEEAC7);
  static const accent200 = Color(0xFFFDD38A);
  static const accent300 = Color(0xFFFCB64D);
  static const accent400 = Color(0xFFFB9D24);
  static const accent500 = Color(0xFFF57B0B);
  static const accent600 = Color(0xFFD95806);
  static const accent700 = Color(0xFFB43A09);
  static const accent800 = Color(0xFF922D0E);
  static const accent900 = Color(0xFF78260F);
  static const accent950 = Color(0xFF451103);
  static const ink50 = Color(0xFFF6F7F9);
  static const ink100 = Color(0xFFECEEF2);
  static const ink200 = Color(0xFFD5DAE2);
  static const ink300 = Color(0xFFB0B9C9);
  static const ink400 = Color(0xFF8594AB);
  static const ink500 = Color(0xFF667691);
  static const ink600 = Color(0xFF515F78);
  static const ink700 = Color(0xFF434D62);
  static const ink800 = Color(0xFF3A4253);
  static const ink900 = Color(0xFF1F2430);
  static const ink950 = Color(0xFF12151C);
  static const success = Color(0xFF16A34A);
  static const warning = Color(0xFFF59E0B);
  static const danger = Color(0xFFDC2626);
  static const info = Color(0xFF2563EB);
}

abstract final class SajhaRadius {
  static const double sm = 6;
  static const double md = 10;
  static const double lg = 16;
  static const double xl = 24;
  static const double full = 9999;
}

abstract final class SajhaSpacing {
  static const double xs = 4;
  static const double sm = 8;
  static const double md = 16;
  static const double lg = 24;
  static const double xl = 32;
  static const double x2xl = 48;
}

abstract final class SajhaFonts {
  static const sans = 'Plus Jakarta Sans';
  static const display = 'Bricolage Grotesque';
  static const mono = 'JetBrains Mono';
}
